/* Generated By:JJTree: Do not edit this line. ASTMyID.h Version ??.?? */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTMyID_H_
#define ASTMyID_H_
#include "SimpleNode.h"


namespace EG3 {
class Parser;


class ASTMyID : public SimpleNode {
private:
	JAVACC_STRING_TYPE name;
public: 
           ASTMyID(int id);
           ASTMyID(Parser *parser, int id);
  virtual ~ASTMyID();

	void setName(JAVACC_STRING_TYPE image);
	JAVACC_STRING_TYPE toString() const;

};

}

#endif
