/* Generated By:JJTree: Do not edit this line. ASTMyID.cc Version ??.?? */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTMyID.h"

namespace EG3 {
  
  ASTMyID::ASTMyID(int id) : SimpleNode(id){
  }

  ASTMyID::ASTMyID(Parser *parser, int id) : SimpleNode(parser, id){
  }
  ASTMyID::~ASTMyID() {
  }

  void  ASTMyID::setName(JAVACC_STRING_TYPE image) {
  	name = image;
  }
  JAVACC_STRING_TYPE  ASTMyID::toString() const {
    return "Identifier: " + name;
  }

}
